sudo: false
language: android

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.android/build-cache

    - node_modules

env:
  global:
    - ANDROID_API_LEVEL=26
    - EMULATOR_API_LEVEL=21
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

before_script:
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install python3-pip
  - npm config set strict-ssl false
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  # setup UI automation
  - sudo npm install -g appium --unsafe-perm=true --allow-root
  - sudo npm install -g wd --unsafe-perm=true --allow-root
  - sudo pip3 install Appium-Python-Client pytest requests
  - appium &
  - git clone https://github.com/kinfoundation/Kin-Stellar-SampleApp-Automation.git
  # setup android emulator
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window -camera-back none -camera-front none -verbose -memory 2048 &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew :sample:assembleDebug
  - ./gradlew :kin-core:test
  - ./gradlew kin-core:assembleDebugAndroidTest
  - adb install -r ./kin-core/build/outputs/apk/androidTest/debug/kin-core-debug-androidTest.apk
  - adb install -r ./sample/build/outputs/apk/debug/sample-debug.apk
  - ./run_android_test_ci.sh
  - python3 -m pytest -v -x ./Kin-Stellar-SampleApp-Automation/Android_Sanity.py
